# Generated by Django 6.0.7 on 2026-08-03 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manufactura", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productionorder",
            old_name="creado_at",
            new_name="created_at",
        ),
    ]
